#! /bin/bash

bash /home/path_to_public/public_html/papervault/generator/you_process.sh
bash /home/path_to_public/public_html/papervault/generator/woo_process.sh
bash /home/path_to_public/public_html/papervault/generator/wme_process.sh
bash /home/path_to_public/public_html/papervault/generator/wlt_process.sh
bash /home/path_to_public/public_html/papervault/generator/wld_process.sh
bash /home/path_to_public/public_html/papervault/generator/wkt_process.sh
bash /home/path_to_public/public_html/papervault/generator/win_process.sh
bash /home/path_to_public/public_html/papervault/generator/wet_process.sh
bash /home/path_to_public/public_html/papervault/generator/wes_process.sh
bash /home/path_to_public/public_html/papervault/generator/wen_process.sh
bash /home/path_to_public/public_html/papervault/generator/wem_process.sh
bash /home/path_to_public/public_html/papervault/generator/wek_process.sh
bash /home/path_to_public/public_html/papervault/generator/wee_process.sh
bash /home/path_to_public/public_html/papervault/generator/voi_process.sh
bash /home/path_to_public/public_html/papervault/generator/twc_process.sh
bash /home/path_to_public/public_html/papervault/generator/tru_process.sh
bash /home/path_to_public/public_html/papervault/generator/tri_process.sh
bash /home/path_to_public/public_html/papervault/generator/tre_process.sh
bash /home/path_to_public/public_html/papervault/generator/tme_process.sh
bash /home/path_to_public/public_html/papervault/generator/tke_process.sh
bash /home/path_to_public/public_html/papervault/generator/tho_process.sh
bash /home/path_to_public/public_html/papervault/generator/tha_process.sh
bash /home/path_to_public/public_html/papervault/generator/sva_process.sh
bash /home/path_to_public/public_html/papervault/generator/sta_process.sh
bash /home/path_to_public/public_html/papervault/generator/spo_process.sh
bash /home/path_to_public/public_html/papervault/generator/sou_process.sh
bash /home/path_to_public/public_html/papervault/generator/she_process.sh
bash /home/path_to_public/public_html/papervault/generator/sew_process.sh
bash /home/path_to_public/public_html/papervault/generator/sem_process.sh
bash /home/path_to_public/public_html/papervault/generator/rih_process.sh
bash /home/path_to_public/public_html/papervault/generator/ric_process.sh
bash /home/path_to_public/public_html/papervault/generator/rhe_process.sh
bash /home/path_to_public/public_html/papervault/generator/rep_process.sh
bash /home/path_to_public/public_html/papervault/generator/rec_process.sh
bash /home/path_to_public/public_html/papervault/generator/pub_process.sh
bash /home/path_to_public/public_html/papervault/generator/pre_process.sh
bash /home/path_to_public/public_html/papervault/generator/pot_process.sh
bash /home/path_to_public/public_html/papervault/generator/pos_process.sh
bash /home/path_to_public/public_html/papervault/generator/plo_process.sh
bash /home/path_to_public/public_html/papervault/generator/pem_process.sh
bash /home/path_to_public/public_html/papervault/generator/pac_process.sh
bash /home/path_to_public/public_html/papervault/generator/owi_process.sh
bash /home/path_to_public/public_html/papervault/generator/ovw_process.sh
bash /home/path_to_public/public_html/papervault/generator/oil_process.sh
bash /home/path_to_public/public_html/papervault/generator/obs_process.sh
bash /home/path_to_public/public_html/papervault/generator/nat_process.sh
bash /home/path_to_public/public_html/papervault/generator/mwe_process.sh
bash /home/path_to_public/public_html/papervault/generator/mts_process.sh
bash /home/path_to_public/public_html/papervault/generator/mss_process.sh
bash /home/path_to_public/public_html/papervault/generator/mou_process.sh
bash /home/path_to_public/public_html/papervault/generator/mon_process.sh
bash /home/path_to_public/public_html/papervault/generator/moh_process.sh
bash /home/path_to_public/public_html/papervault/generator/moe_process.sh
bash /home/path_to_public/public_html/papervault/generator/mns_process.sh
bash /home/path_to_public/public_html/papervault/generator/mad_process.sh
bash /home/path_to_public/public_html/papervault/generator/lxt_process.sh
bash /home/path_to_public/public_html/papervault/generator/lwt_process.sh
bash /home/path_to_public/public_html/papervault/generator/lwp_process.sh
bash /home/path_to_public/public_html/papervault/generator/lwn_process.sh
bash /home/path_to_public/public_html/papervault/generator/lvc_process.sh
bash /home/path_to_public/public_html/papervault/generator/lup_process.sh
bash /home/path_to_public/public_html/papervault/generator/lum_process.sh
bash /home/path_to_public/public_html/papervault/generator/lre_process.sh
bash /home/path_to_public/public_html/papervault/generator/low_process.sh
bash /home/path_to_public/public_html/papervault/generator/lou_process.sh
bash /home/path_to_public/public_html/papervault/generator/loj_process.sh
bash /home/path_to_public/public_html/papervault/generator/loe_process.sh
bash /home/path_to_public/public_html/papervault/generator/loa_process.sh
bash /home/path_to_public/public_html/papervault/generator/lmd_process.sh
bash /home/path_to_public/public_html/papervault/generator/lic_process.sh
bash /home/path_to_public/public_html/papervault/generator/lex_process.sh
bash /home/path_to_public/public_html/papervault/generator/let_process.sh
bash /home/path_to_public/public_html/papervault/generator/lep_process.sh
bash /home/path_to_public/public_html/papervault/generator/lee_process.sh
bash /home/path_to_public/public_html/papervault/generator/leb_process.sh
bash /home/path_to_public/public_html/papervault/generator/lde_process.sh
bash /home/path_to_public/public_html/papervault/generator/ldd_process.sh
bash /home/path_to_public/public_html/papervault/generator/laf_process.sh
bash /home/path_to_public/public_html/papervault/generator/lac_process.sh
bash /home/path_to_public/public_html/papervault/generator/ksf_process.sh
bash /home/path_to_public/public_html/papervault/generator/kre_process.sh
bash /home/path_to_public/public_html/papervault/generator/kns_process.sh
bash /home/path_to_public/public_html/papervault/generator/kle_process.sh
bash /home/path_to_public/public_html/papervault/generator/kew_process.sh
bash /home/path_to_public/public_html/papervault/generator/kev_process.sh
bash /home/path_to_public/public_html/papervault/generator/keu_process.sh
bash /home/path_to_public/public_html/papervault/generator/ket_process.sh
bash /home/path_to_public/public_html/papervault/generator/kes_process.sh
bash /home/path_to_public/public_html/papervault/generator/ker_process.sh
bash /home/path_to_public/public_html/papervault/generator/ken_process.sh
bash /home/path_to_public/public_html/papervault/generator/kem_process.sh
bash /home/path_to_public/public_html/papervault/generator/kel_process.sh
bash /home/path_to_public/public_html/papervault/generator/kek_process.sh
bash /home/path_to_public/public_html/papervault/generator/keh_process.sh
bash /home/path_to_public/public_html/papervault/generator/keg_process.sh
bash /home/path_to_public/public_html/papervault/generator/ked_process.sh
bash /home/path_to_public/public_html/papervault/generator/kec_process.sh
bash /home/path_to_public/public_html/papervault/generator/jef_process.sh
bash /home/path_to_public/public_html/papervault/generator/jak_process.sh
bash /home/path_to_public/public_html/papervault/generator/jac_process.sh
bash /home/path_to_public/public_html/papervault/generator/itx_process.sh
bash /home/path_to_public/public_html/papervault/generator/int_process.sh
bash /home/path_to_public/public_html/papervault/generator/ide_process.sh
bash /home/path_to_public/public_html/papervault/generator/ida_process.sh
bash /home/path_to_public/public_html/papervault/generator/hzh_process.sh
bash /home/path_to_public/public_html/papervault/generator/hop_process.sh
bash /home/path_to_public/public_html/papervault/generator/hic_process.sh
bash /home/path_to_public/public_html/papervault/generator/haz_process.sh
bash /home/path_to_public/public_html/papervault/generator/hao_process.sh
bash /home/path_to_public/public_html/papervault/generator/haf_process.sh
bash /home/path_to_public/public_html/papervault/generator/gut_process.sh
bash /home/path_to_public/public_html/papervault/generator/gua_process.sh
bash /home/path_to_public/public_html/papervault/generator/geo_process.sh
bash /home/path_to_public/public_html/papervault/generator/frc_process.sh
bash /home/path_to_public/public_html/papervault/generator/fra_process.sh
bash /home/path_to_public/public_html/papervault/generator/fcc_process.sh
bash /home/path_to_public/public_html/papervault/generator/far_process.sh
bash /home/path_to_public/public_html/papervault/generator/fai_process.sh
bash /home/path_to_public/public_html/papervault/generator/exa_process.sh
bash /home/path_to_public/public_html/papervault/generator/eve_process.sh
bash /home/path_to_public/public_html/papervault/generator/elz_process.sh
bash /home/path_to_public/public_html/papervault/generator/elk_process.sh
bash /home/path_to_public/public_html/papervault/generator/eli_process.sh
bash /home/path_to_public/public_html/papervault/generator/ech_process.sh
bash /home/path_to_public/public_html/papervault/generator/dru_process.sh
bash /home/path_to_public/public_html/papervault/generator/dol_process.sh
bash /home/path_to_public/public_html/papervault/generator/dlt_process.sh
bash /home/path_to_public/public_html/papervault/generator/dld_process.sh
bash /home/path_to_public/public_html/papervault/generator/das_process.sh
bash /home/path_to_public/public_html/papervault/generator/dan_process.sh
bash /home/path_to_public/public_html/papervault/generator/dai_process.sh
bash /home/path_to_public/public_html/papervault/generator/dac_process.sh
bash /home/path_to_public/public_html/papervault/generator/cyn_process.sh
bash /home/path_to_public/public_html/papervault/generator/cro_process.sh
bash /home/path_to_public/public_html/papervault/generator/cri_process.sh
bash /home/path_to_public/public_html/papervault/generator/clm_process.sh
bash /home/path_to_public/public_html/papervault/generator/cla_process.sh
bash /home/path_to_public/public_html/papervault/generator/cjd_process.sh
bash /home/path_to_public/public_html/papervault/generator/cit_process.sh
bash /home/path_to_public/public_html/papervault/generator/cho_process.sh
bash /home/path_to_public/public_html/papervault/generator/cen_process.sh
bash /home/path_to_public/public_html/papervault/generator/ced_process.sh
bash /home/path_to_public/public_html/papervault/generator/bre_process.sh
bash /home/path_to_public/public_html/papervault/generator/brc_process.sh
bash /home/path_to_public/public_html/papervault/generator/bou_process.sh
bash /home/path_to_public/public_html/papervault/generator/blu_process.sh
bash /home/path_to_public/public_html/papervault/generator/big_process.sh
bash /home/path_to_public/public_html/papervault/generator/bee_process.sh
bash /home/path_to_public/public_html/papervault/generator/bar_process.sh
bash /home/path_to_public/public_html/papervault/generator/ame_process.sh
bash /home/path_to_public/public_html/papervault/generator/afr_process.sh
bash /home/path_to_public/public_html/papervault/generator/ada_process.sh
