#! /bin/bash

bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ada
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh afr
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ame
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh bar
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh bee
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh big
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh blu
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh bou
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh brc
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh bre
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ced
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cen
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cho
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cit
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cjd
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cla
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh clm
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cri
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cro
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh cyn
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dac
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dai
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dan
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh das
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dld
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dlt
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dol
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh dru
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ech
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh eli
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh elk
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh elz
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh eve
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh exa
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh fai
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh far
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh fcc
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh fra
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh frc
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh geo
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh gua
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh gut
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh haf
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh hao
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh haz
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh hic
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh hop
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh hzh
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ida
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ide
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh int
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh itx
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh jac
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh jak
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh jef
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kec
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ked
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh keg
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh keh
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kek
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kel
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kem
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ken
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ker
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kes
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ket
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh keu
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kev
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kew
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kle
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kns
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh kre
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ksf
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lac
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh laf
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ldd
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lde
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh leb
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lee
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lep
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh let
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lex
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lic
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lmd
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh loa
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh loe
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh loj
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lou
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh low
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lre
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lum
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lup
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lvc
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lwn
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lwp
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lwt
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh lxt
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mad
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mns
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh moe
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh moh
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mon
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mou
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mss
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mts
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh mwe
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh nat
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh obs
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh oil
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ovw
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh owi
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh pac
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh pem
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh plo
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh pos
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh pot
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh pre
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh pub
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh rec
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh rep
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh rhe
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh ric
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh rih
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh sem
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh sew
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh she
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh sou
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh spo
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh sta
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh sva
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tha
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tho
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tke
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tme
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tre
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tri
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh tru
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh twc
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh voi
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wee
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wek
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wem
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wen
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wes
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wet
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh win
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wkt
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wld
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wlt
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh wme
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh woo
bash /home/path_to_public/public_html/cgi-bin/gathercsv.sh you
